****** Local formatted examples with non-posted traces ******
{"severity": "INFO", "time": "2018-07-31T18:42:43.067931", "sourceLocation": {"file": "/Users/windet01/Files/Code/logtracer/examples/flask/server.py", "line": 89, "function": "run_flask_server"}, "message": "root - Starting flask server on http://localhost:5005."}
 * Serving Flask app "demoFlaskApp" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off


FLASK CALLBACKS EXAMPLE
Single call to Flask root endpoint:
{"severity": "INFO", "time": "2018-07-31T18:42:44.091275", "sourceLocation": {"file": "/Users/windet01/Files/Code/logtracer/logtracer/helpers/flask/callbacks.py", "line": 16, "function": "execute_before_request"}, "message": "demoApp - GET - http://localhost:5005/", "traceId": "0465b93320fc24cc9835ccf4a4982e17", "spanId": "3c6e41826026a086"}
{"severity": "INFO", "time": "2018-07-31T18:42:44.092800", "sourceLocation": {"file": "/Users/windet01/Files/Code/logtracer/logtracer/helpers/flask/callbacks.py", "line": 34, "function": "execute_after_request"}, "message": "demoApp - 200 OK - http://localhost:5005/", "traceId": "0465b93320fc24cc9835ccf4a4982e17", "spanId": "3c6e41826026a086"}
Done


Double call to Flask endpoints:
{"severity": "INFO", "time": "2018-07-31T18:42:44.108907", "sourceLocation": {"file": "/Users/windet01/Files/Code/logtracer/logtracer/helpers/flask/callbacks.py", "line": 16, "function": "execute_before_request"}, "message": "demoApp - GET - http://localhost:5005/doublehttp", "traceId": "6439310f27f712a6910d7a56f376e195", "spanId": "71990ebb9b4d1822"}
{"severity": "INFO", "time": "2018-07-31T18:42:44.127015", "sourceLocation": {"file": "/Users/windet01/Files/Code/logtracer/logtracer/helpers/flask/callbacks.py", "line": 16, "function": "execute_before_request"}, "message": "demoApp - GET - http://localhost:5005/", "traceId": "6439310f27f712a6910d7a56f376e195", "spanId": "54f1bf972a90e910"}
{"severity": "INFO", "time": "2018-07-31T18:42:44.129336", "sourceLocation": {"file": "/Users/windet01/Files/Code/logtracer/logtracer/helpers/flask/callbacks.py", "line": 34, "function": "execute_after_request"}, "message": "demoApp - 200 OK - http://localhost:5005/", "traceId": "6439310f27f712a6910d7a56f376e195", "spanId": "54f1bf972a90e910"}
{"severity": "INFO", "time": "2018-07-31T18:42:44.136034", "sourceLocation": {"file": "/Users/windet01/Files/Code/logtracer/logtracer/helpers/flask/callbacks.py", "line": 34, "function": "execute_after_request"}, "message": "demoApp - 200 OK - http://localhost:5005/doublehttp", "traceId": "6439310f27f712a6910d7a56f376e195", "spanId": "71990ebb9b4d1822"}
Done


Two calls to endpoints excluded from Trace API:
{"severity": "INFO", "time": "2018-07-31T18:42:44.147917", "sourceLocation": {"file": "/Users/windet01/Files/Code/logtracer/logtracer/helpers/flask/callbacks.py", "line": 16, "function": "execute_before_request"}, "message": "demoApp - GET - http://localhost:5005/excludefull", "traceId": "24964f2978b5cc84db0f62e65ce553af", "spanId": "9a21cff2fb07fe4a"}
{"severity": "INFO", "time": "2018-07-31T18:42:44.149259", "sourceLocation": {"file": "/Users/windet01/Files/Code/logtracer/logtracer/helpers/flask/callbacks.py", "line": 34, "function": "execute_after_request"}, "message": "demoApp - 200 OK - http://localhost:5005/excludefull", "traceId": "24964f2978b5cc84db0f62e65ce553af", "spanId": "9a21cff2fb07fe4a"}
{"severity": "INFO", "time": "2018-07-31T18:42:44.159465", "sourceLocation": {"file": "/Users/windet01/Files/Code/logtracer/logtracer/helpers/flask/callbacks.py", "line": 16, "function": "execute_before_request"}, "message": "demoApp - GET - http://localhost:5005/excludepartial", "traceId": "790a37552464ddd61a5f80fa595821ab", "spanId": "124fa7ce8f2fcc12"}
{"severity": "INFO", "time": "2018-07-31T18:42:44.160819", "sourceLocation": {"file": "/Users/windet01/Files/Code/logtracer/logtracer/helpers/flask/callbacks.py", "line": 34, "function": "execute_after_request"}, "message": "demoApp - 200 OK - http://localhost:5005/excludepartial", "traceId": "790a37552464ddd61a5f80fa595821ab", "spanId": "124fa7ce8f2fcc12"}
Done


Call to handled exception:
{"severity": "INFO", "time": "2018-07-31T18:42:44.171164", "sourceLocation": {"file": "/Users/windet01/Files/Code/logtracer/logtracer/helpers/flask/callbacks.py", "line": 16, "function": "execute_before_request"}, "message": "demoApp - GET - http://localhost:5005/handledexception", "traceId": "c4d1a4ab77ec11b2f4ec3b0d2db2d974", "spanId": "fcb14173127c95ed"}
{"severity": "ERROR", "time": "2018-07-31T18:42:44.172701", "sourceLocation": {"file": "/Users/windet01/Files/Code/logtracer/logtracer/helpers/flask/decorators.py", "line": 17, "function": "wrapper"}, "message": "demoApp - Exception: HandledException(This is a handled Exception!)\nTraceback:\n  File \"/Users/windet01/Files/Code/logtracer/venv/lib/python3.7/site-packages/flask/app.py\", line 1813, in full_dispatch_request\n    rv = self.dispatch_request()\n\n  File \"/Users/windet01/Files/Code/logtracer/venv/lib/python3.7/site-packages/flask/app.py\", line 1799, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n\n  File \"/Users/windet01/Files/Code/logtracer/examples/flask/server.py\", line 73, in handled_exception\n    raise HandledException('This is a handled Exception!')\n", "traceId": "c4d1a4ab77ec11b2f4ec3b0d2db2d974", "spanId": "fcb14173127c95ed"}
{"severity": "ERROR", "time": "2018-07-31T18:42:44.176042", "sourceLocation": {"file": "/Users/windet01/Files/Code/logtracer/logtracer/helpers/flask/callbacks.py", "line": 32, "function": "execute_after_request"}, "message": "demoApp - 500 INTERNAL SERVER ERROR - http://localhost:5005/handledexception", "traceId": "c4d1a4ab77ec11b2f4ec3b0d2db2d974", "spanId": "fcb14173127c95ed"}
Call to unhandled exception:
{"severity": "INFO", "time": "2018-07-31T18:42:44.187187", "sourceLocation": {"file": "/Users/windet01/Files/Code/logtracer/logtracer/helpers/flask/callbacks.py", "line": 16, "function": "execute_before_request"}, "message": "demoApp - GET - http://localhost:5005/unhandledexception", "traceId": "7cb1e67cce0a966be59b244c1ec7adb8", "spanId": "1e24569ed9607bcc"}
{"severity": "ERROR", "time": "2018-07-31T18:42:44.188484", "sourceLocation": {"file": "/Users/windet01/Files/Code/logtracer/venv/lib/python3.7/site-packages/flask/app.py", "line": 1761, "function": "log_exception"}, "message": "flask.app - Exception: UnhandledException(This is an unhandled Exception!)\nTraceback:\n  File \"/Users/windet01/Files/Code/logtracer/venv/lib/python3.7/site-packages/flask/app.py\", line 2292, in wsgi_app\n    response = self.full_dispatch_request()\n\n  File \"/Users/windet01/Files/Code/logtracer/venv/lib/python3.7/site-packages/flask/app.py\", line 1815, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n\n  File \"/Users/windet01/Files/Code/logtracer/venv/lib/python3.7/site-packages/flask/app.py\", line 1718, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n\n  File \"/Users/windet01/Files/Code/logtracer/venv/lib/python3.7/site-packages/flask/_compat.py\", line 35, in reraise\n    raise value\n\n  File \"/Users/windet01/Files/Code/logtracer/venv/lib/python3.7/site-packages/flask/app.py\", line 1813, in full_dispatch_request\n    rv = self.dispatch_request()\n\n  File \"/Users/windet01/Files/Code/logtracer/venv/lib/python3.7/site-packages/flask/app.py\", line 1799, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n\n  File \"/Users/windet01/Files/Code/logtracer/examples/flask/server.py\", line 78, in unhandled_exception\n    raise UnhandledException('This is an unhandled Exception!')\n", "traceId": "7cb1e67cce0a966be59b244c1ec7adb8", "spanId": "1e24569ed9607bcc"}
Done


****** GCP formatted examples with posted traces ******
/Users/windet01/Files/Code/logtracer/venv/lib/python3.7/site-packages/google/auth/_default.py:66: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)


FLASK CALLBACKS EXAMPLE
Single call to Flask root endpoint:
{"severity": "INFO", "time": "2018-07-31T18:42:45.995831", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/logtracer/logtracer/helpers/flask/callbacks.py", "line": 16, "function": "execute_before_request"}, "message": "demoApp - GET - http://localhost:5005/", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/0c5691f844ec7e44cd40b11d032b2c5c", "logging.googleapis.com/spanId": "15b08f0f8ed7567e"}
{"severity": "INFO", "time": "2018-07-31T18:42:45.997772", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/logtracer/logtracer/helpers/flask/callbacks.py", "line": 34, "function": "execute_after_request"}, "message": "demoApp - 200 OK - http://localhost:5005/", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/0c5691f844ec7e44cd40b11d032b2c5c", "logging.googleapis.com/spanId": "15b08f0f8ed7567e"}
Done


Double call to Flask endpoints:
{"severity": "INFO", "time": "2018-07-31T18:42:46.015485", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/logtracer/logtracer/helpers/flask/callbacks.py", "line": 16, "function": "execute_before_request"}, "message": "demoApp - GET - http://localhost:5005/doublehttp", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/076c7bd4a73eba7703dc5ffb406c0d0e", "logging.googleapis.com/spanId": "d53cc29549129ee9"}
{"severity": "INFO", "time": "2018-07-31T18:42:46.032672", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/logtracer/logtracer/helpers/flask/callbacks.py", "line": 16, "function": "execute_before_request"}, "message": "demoApp - GET - http://localhost:5005/", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/076c7bd4a73eba7703dc5ffb406c0d0e", "logging.googleapis.com/spanId": "251d2f3a0dd92c81"}
{"severity": "INFO", "time": "2018-07-31T18:42:46.034081", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/logtracer/logtracer/helpers/flask/callbacks.py", "line": 34, "function": "execute_after_request"}, "message": "demoApp - 200 OK - http://localhost:5005/", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/076c7bd4a73eba7703dc5ffb406c0d0e", "logging.googleapis.com/spanId": "251d2f3a0dd92c81"}
{"severity": "INFO", "time": "2018-07-31T18:42:46.042633", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/logtracer/logtracer/helpers/flask/callbacks.py", "line": 34, "function": "execute_after_request"}, "message": "demoApp - 200 OK - http://localhost:5005/doublehttp", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/076c7bd4a73eba7703dc5ffb406c0d0e", "logging.googleapis.com/spanId": "d53cc29549129ee9"}
Done


Two calls to endpoints excluded from Trace API:
{"severity": "INFO", "time": "2018-07-31T18:42:46.055726", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/logtracer/logtracer/helpers/flask/callbacks.py", "line": 16, "function": "execute_before_request"}, "message": "demoApp - GET - http://localhost:5005/excludefull", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/dc0ee16b5829d2aa0ae5b3d30658c17d", "logging.googleapis.com/spanId": "e57914c4671bdaa5"}
{"severity": "INFO", "time": "2018-07-31T18:42:46.057109", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/logtracer/logtracer/helpers/flask/callbacks.py", "line": 34, "function": "execute_after_request"}, "message": "demoApp - 200 OK - http://localhost:5005/excludefull", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/dc0ee16b5829d2aa0ae5b3d30658c17d", "logging.googleapis.com/spanId": "e57914c4671bdaa5"}
{"severity": "INFO", "time": "2018-07-31T18:42:46.095072", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/logtracer/logtracer/helpers/flask/callbacks.py", "line": 16, "function": "execute_before_request"}, "message": "demoApp - GET - http://localhost:5005/excludepartial", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/0ca1f251eebbabca30ad0592b240edef", "logging.googleapis.com/spanId": "79b4293ffe5f7935"}
{"severity": "INFO", "time": "2018-07-31T18:42:46.096439", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/logtracer/logtracer/helpers/flask/callbacks.py", "line": 34, "function": "execute_after_request"}, "message": "demoApp - 200 OK - http://localhost:5005/excludepartial", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/0ca1f251eebbabca30ad0592b240edef", "logging.googleapis.com/spanId": "79b4293ffe5f7935"}
Done


Call to handled exception:
{"severity": "INFO", "time": "2018-07-31T18:42:46.113148", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/logtracer/logtracer/helpers/flask/callbacks.py", "line": 16, "function": "execute_before_request"}, "message": "demoApp - GET - http://localhost:5005/handledexception", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/7a6c9efa713464bd450c1549ecb97f64", "logging.googleapis.com/spanId": "c584f11bdf865b81"}
{"severity": "ERROR", "time": "2018-07-31T18:42:46.114682", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/logtracer/logtracer/helpers/flask/decorators.py", "line": 17, "function": "wrapper"}, "message": "demoApp - Exception: HandledException(This is a handled Exception!)\nTraceback:\n  File \"/Users/windet01/Files/Code/logtracer/venv/lib/python3.7/site-packages/flask/app.py\", line 1813, in full_dispatch_request\n    rv = self.dispatch_request()\n\n  File \"/Users/windet01/Files/Code/logtracer/venv/lib/python3.7/site-packages/flask/app.py\", line 1799, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n\n  File \"/Users/windet01/Files/Code/logtracer/examples/flask/server.py\", line 73, in handled_exception\n    raise HandledException('This is a handled Exception!')\n", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/7a6c9efa713464bd450c1549ecb97f64", "logging.googleapis.com/spanId": "c584f11bdf865b81"}
{"severity": "ERROR", "time": "2018-07-31T18:42:46.117064", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/logtracer/logtracer/helpers/flask/callbacks.py", "line": 32, "function": "execute_after_request"}, "message": "demoApp - 500 INTERNAL SERVER ERROR - http://localhost:5005/handledexception", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/7a6c9efa713464bd450c1549ecb97f64", "logging.googleapis.com/spanId": "c584f11bdf865b81"}
Call to unhandled exception:
{"severity": "INFO", "time": "2018-07-31T18:42:46.142153", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/logtracer/logtracer/helpers/flask/callbacks.py", "line": 16, "function": "execute_before_request"}, "message": "demoApp - GET - http://localhost:5005/unhandledexception", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/10275a814676fb416f67a771c253a2d8", "logging.googleapis.com/spanId": "130e559927e84b18"}
{"severity": "ERROR", "time": "2018-07-31T18:42:46.143249", "logging.googleapis.com/sourceLocation": {"file": "/Users/windet01/Files/Code/logtracer/venv/lib/python3.7/site-packages/flask/app.py", "line": 1761, "function": "log_exception"}, "message": "flask.app - Exception: UnhandledException(This is an unhandled Exception!)\nTraceback:\n  File \"/Users/windet01/Files/Code/logtracer/venv/lib/python3.7/site-packages/flask/app.py\", line 2292, in wsgi_app\n    response = self.full_dispatch_request()\n\n  File \"/Users/windet01/Files/Code/logtracer/venv/lib/python3.7/site-packages/flask/app.py\", line 1815, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n\n  File \"/Users/windet01/Files/Code/logtracer/venv/lib/python3.7/site-packages/flask/app.py\", line 1718, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n\n  File \"/Users/windet01/Files/Code/logtracer/venv/lib/python3.7/site-packages/flask/_compat.py\", line 35, in reraise\n    raise value\n\n  File \"/Users/windet01/Files/Code/logtracer/venv/lib/python3.7/site-packages/flask/app.py\", line 1813, in full_dispatch_request\n    rv = self.dispatch_request()\n\n  File \"/Users/windet01/Files/Code/logtracer/venv/lib/python3.7/site-packages/flask/app.py\", line 1799, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n\n  File \"/Users/windet01/Files/Code/logtracer/examples/flask/server.py\", line 78, in unhandled_exception\n    raise UnhandledException('This is an unhandled Exception!')\n", "logging.googleapis.com/trace": "projects/bbc-connected-data/traces/10275a814676fb416f67a771c253a2d8", "logging.googleapis.com/spanId": "130e559927e84b18"}
Done